//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class docentes_cursos
    {
        public int id_dictado { get; set; }
        public string desc_materia { get; set; }
        public int id_curso { get; set; }
        public int id_docente { get; set; }
        public int cargo { get; set; }
    }
}
